const imagesLink = {
  EUR: require('./../assets/images/european-union-flag-round-medium.png'),
  BGN: require('./../assets/images/bulgaria-flag-round-medium.png'),
  NZD: require('./../assets/images/new-zealand-flag-round-medium.png'),
  ILS: require('./../assets/images/israel-flag-round-medium.png'),
  RUB: require('./../assets/images/russia-flag-round-medium.png'),
  CAD: require('./../assets/images/canada-flag-round-medium.png'),
  USD: require('./../assets/images/united-states-of-america-flag-round-medium.png'),
  PHP: require('./../assets/images/philippines-flag-round-medium.png'),
  CHF: require('./../assets/images/switzerland-flag-round-medium.png'),
  ZAR: require('./../assets/images/south-africa-flag-round-medium.png'),
  AUD: require('./../assets/images/australia-flag-round-medium.png'),
  JPY: require('./../assets/images/japan-flag-round-medium.png'),
  TRY: require('./../assets/images/turkey-flag-round-medium.png'),
  HKD: require('./../assets/images/china-flag-round-medium.png'),
  MYR: require('./../assets/images/malaysia-flag-round-medium.png'),
  THB: require('./../assets/images/thailand-flag-round-medium.png'),
  HRK: require('./../assets/images/croatia-flag-round-medium.png'),
  NOK: require('./../assets/images/norway-flag-round-medium.png'),
  IDR: require('./../assets/images/indonesia-flag-round-medium.png'),
  DKK: require('./../assets/images/denmark-flag-round-medium.png'),
  CZK: require('./../assets/images/czech-republic-flag-round-medium.png'),
  HUF: require('./../assets/images/hungary-flag-round-medium.png'),
  GBP: require('./../assets/images/united-kingdom-flag-round-medium.png'),
  MXN: require('./../assets/images/mexico-flag-round-medium.png'),
  KRW: require('./../assets/images/south-korea-flag-round-medium.png'),
  ISK: require('./../assets/images/iceland-flag-round-medium.png'),
  SGD: require('./../assets/images/singapore-flag-round-medium.png'),
  BRL: require('./../assets/images/brazil-flag-round-medium.png'),
  PLN: require('./../assets/images/poland-flag-round-medium.png'),
  INR: require('./../assets/images/india-flag-round-medium.png'),
  RON: require('./../assets/images/romania-flag-round-medium.png'),
  CNY: require('./../assets/images/china-flag-round-medium.png'),
  SEK: require('./../assets/images/sweden-flag-round-medium.png'),
}

export default imagesLink